export const FETCH_CATEG_START = 'FETCH_CATEG_START';
export const FETCH_CATEG_SUCCESS = 'FETCH_CATEG_SUCCESS';
export const FETCH_CATEG_END = 'FETCH_CATEG_END';
export const FETCH_FAIL = 'FETCH_FAIL';
